import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from "@angular/router";
import { IonicModule, IonIcon } from "@ionic/angular";
import { addIcons } from 'ionicons';
import { logInSharp, mailSharp, personAddSharp, refreshSharp } from 'ionicons/icons';
import { AppModule } from "src/app/app.module";
import { AuthGatewayService } from "../../services/auth-gateway.service.ts.js";
import { PASSWORD_STRENGTH_MESSAGE, PASSWORD_STRENGTH_MESSAGE_LIST, PASSWORD_STRENGTH_REGEX, passwordsMatchValidator } from "src/app/common/validators/password-validators.js";
import { AuthService } from "../../services/auth.service.js";
import { combineLatest, finalize, startWith } from "rxjs";
import { CommonService } from "src/app/common/services/common.service.js";


@Component({
    selector: 'app-register',
    templateUrl: './register.page.html',
    standalone: true,
    imports: [AppModule, IonicModule, ReactiveFormsModule]
})

export class RegisterPage implements OnInit {
    public registerForm: FormGroup;
    public autoGeneratedEmail = ''
    protected readonly userType = 'staff'
    protected isLoading = false;
    protected readonly passwordRequirementsMessageList = PASSWORD_STRENGTH_MESSAGE_LIST;
    protected readonly errMsgConfirmPassword = 'Passwords do not match.';

    constructor(
        private FormBuilder: FormBuilder,
        private Router: Router,
        private AuthGatewayService: AuthGatewayService,
        private AuthService: AuthService,
        private CommonService: CommonService
    ) {
        this.registerForm = this.FormBuilder.group(
            { // validation for input fields
                email: ['', [Validators.required, Validators.email]],
                username: ['', [Validators.required]],
                first_name: ['', [Validators.required]],
                last_name: ['', [Validators.required]],
                password: ['', [Validators.required, Validators.pattern(PASSWORD_STRENGTH_REGEX)]],
                confirm_password: ['', [Validators.required]],
            },
            { validators: [passwordsMatchValidator('password', 'confirm_password')] },
        );
        addIcons({ logInSharp, personAddSharp, mailSharp, refreshSharp });
    }

    ngOnInit() {
        const firstNameCtrl = this.registerForm.get('first_name');
        const lastNameCtrl = this.registerForm.get('last_name');
        if (firstNameCtrl == null || lastNameCtrl == null) {
            return;
        }
        combineLatest([
            firstNameCtrl.valueChanges.pipe(startWith(firstNameCtrl.value ?? '')),
            lastNameCtrl.valueChanges.pipe(startWith(lastNameCtrl.value ?? '')),
        ]).subscribe(([firstName, lastName]) => {
            if (firstName && lastName) {
                this.autoGeneratedEmail = this.AuthService.generateEmail({
                    firstName: String(firstName ?? ''),
                    lastName: String(lastName ?? ''),
                });
                this.registerForm.get('email')?.setValue(this.autoGeneratedEmail);
            } else {
                this.registerForm.get('email')?.setValue('');
            }

        });
    }

    /** Group validator sets `passwordsMismatch` on the form, not on `confirm_password`. */
    protected showConfirmPasswordMismatchError(): boolean {
        const fieldStateConfirmPW = this.registerForm.get('confirm_password');
        const interacted =
            (fieldStateConfirmPW?.touched ?? false) ||
            (fieldStateConfirmPW?.dirty ?? false);
        return interacted && this.registerForm.getError('passwordsMismatch') != null;
    }

    public registerUser = () => {
        this.isLoading = true;
        this.AuthGatewayService.register(this.registerForm.value)
            .pipe(finalize(() => {
                this.isLoading = false
            }))
            .subscribe({
                next: (res: any) => {
                    if (!res?.success) {
                        this.CommonService.createToast({
                            message: String(res?.message ?? 'Register failed'),
                            duration: 2,
                            color: 'danger',
                        })
                        return;
                    }

                    this.CommonService.createToast({
                        message: 'Register successful',
                        duration: 4,
                        color: 'success',
                    })
                    this.Router.navigate(['/auth/register/success']);
                },
                error: (error: any) => {
                    this.CommonService.createToast({
                        message: error?.error?.message,
                        duration: 4,
                        color: 'danger',
                    })
                }
            })
    }

}
